Job to fetch stats from old Numbers API
betagouv/audioconf pull request #104
Opened 2020-12-16 15:35 UTC by estellecomment

2020-12-16 21:47 UTC, jdauphant commented on docker-compose-no-web.yml
> +      - "1025:25"
tu peux utiliser docker-compose et ne pas lancer tous les container.
Tu peux faire "docker-compose up db" par exemple

2020-12-18 18:03 UTC, jdauphant commented on jobs/fetchNumbersStats.js
> +      process.exit()
Ça me fait bizarre de voir ça au milieu du code. On ne peut pas utiliser la base de prod ? (les données persos ont été filtré)

2020-12-18 18:04 UTC, jdauphant commented
Proposition :
- Ajouter la table callInfos ou call dans la base de prod
- Faire un cron job de récupération de donnée
- Dans une app séparé sur scalingo
   - Faire en sorte que seul 1 job soit lancé
   - Elle écrit les données dans la base de prod

2020-12-24 11:17 UTC, pom421 commented on docker-compose-no-web.yml
> +      - "1025:25"
Oui, on peut faire `docker-compose up db maildev` en développement 👍

2020-12-24 16:28 UTC, pom421 commented
Questions à se poser:
- vérifier lors du déploiement d'une nouvelle version dans l'app scalingo qui lance le job, que le container web est bien arrêté et que le container clock est bien lancé (le Profile prévoit ces 2 containers)
- vérifier que tous les FEATURE sont à false, sauf FEATURE_JOB_OVH_STATS
- vérifier que la DATABASE_URL de cette app Scalingo, pointe bien vers la DB d'audioconf-test
- Qui va lancer le Knex migrate? Vu qu'il y aura 2 apps Scalingo qui pointe vers la même DB et qui prévoit de faire un migrate (app.json) ?

2020-12-30 20:33 UTC, jdauphant commented on jobs/fetchOVHStats.js
> +// 3. Get history for a room with `/telephony/{process.env.OVH_ROOM_ACCOUNT_NUMBER}/conference/{phoneNumber}/rooms/{roomNumber}/histories`
Ce n'est plus à jour

2020-12-30 20:43 UTC, jdauphant commented on jobs/fetchOVHStats.js
> +  let ovhClient = config.USE_OVH_ROOM_API
ça ne marche pas comme flag ^^, c'est toujours faux

2020-12-31 19:11 UTC, jdauphant commented on cron.js
> +    cronTime: "30 10 * * *", // everyday at 10:30 for testing purpose (at the end, willl be run every 5 minutes)
Il faut faire une fois par nuit, je pense (à un horaire différent des autres jobs)

2020-12-31 19:11 UTC, jdauphant requested changes
Une fois par nuit serait bien

2020-12-31 19:14 UTC, jdauphant commented on cron.js
> +    cronTime: "30 10 * * *", // everyday at 10:30 for testing purpose (at the end, willl be run every 5 minutes)
Il faut faire attention, des choses comme ça, ça peut passer en prod une fois que c'est commit (il vaut mieux mettre une variable avec un defaut qui passe en prod, un peu comme le DRY_RUN)

2021-01-04 13:10 UTC, estellecomment commented on cron.js
> +    isActive: config.FEATURE_JOB_OVH_STATS,
on a deja un job qui fait des stats sur OVH, donc un meilleur nom ca serait FEATURE_JOB_CALLS_STATS

2021-01-04 13:11 UTC, estellecomment commented on cron.js
> +    cronTime: "30 10 * * *", // everyday at 10:30 for testing purpose (at the end, willl be run every 5 minutes)
je comprends pas. Par default FEATURE_JOB_OVH_STATS = false donc le job ne tourne pas, ca suffit ?

2021-01-04 13:18 UTC, estellecomment reviewed
Reste à faire : 
 - on n'a plus d'ancien API, enlever les flags et variantes devenues inutiles
 - verifier que le job marche bien avec le nouvel API (c'est peut etre deja le cas si ca marche en prod!)
 - bouger du code d'appel d'API dans conferences.js
 - renommer le job, c'est pas clair la difference entre les deux jobs de stats
 - changer l'heure du job : le mettre 1fois/j, dans la nuit, heure differente que les autres jobs
 - verifier que les migrations marchent tjs correctement quand il y a 2 serveurs sur la meme DB (je pense que oui, la db contient du data sur quelles migrations ont tourné)

2021-01-04 13:21 UTC, jdauphant commented
"verifier que les migrations marchent tjs correctement quand il y a 2 serveurs sur la meme DB (je pense que oui, la db contient du data sur quelles migrations ont tourné)" -> oui, et on ne peut plus toucher la migration sur cette PR, j'ai poussé en prod pour avoir les données

2021-01-04 13:41 UTC, pom421 commented on jobs/fetchOVHStats.js
> +// 3. Get history for a room with `/telephony/{process.env.OVH_ROOM_ACCOUNT_NUMBER}/conference/{phoneNumber}/rooms/{roomNumber}/histories`
Julien m'a expliqué depuis que la même api pouvait être utilisé pour l'API téléphony et l'API rooms, ce que je ne savais pas à l'époque. Commentaires a supprimer donc.

2021-01-04 13:43 UTC, pom421 commented on cron.js
> +    cronTime: "30 10 * * *", // everyday at 10:30 for testing purpose (at the end, willl be run every 5 minutes)
Je dirais que si.

2021-01-05 14:16 UTC, jdauphant commented
@estellecomment On peut relancer la review ?

2021-01-06 09:46 UTC, estellecomment commented
Reste à faire : 
 - le nom de la var de STATS_SMALL_RUN est chelou je trouve
 - la review app crash (peut etre que c'est quand ya aucun cron job qui start, du coup le programme termine, et scalingo interprete ca comme un crash)

2021-01-06 09:55 UTC, estellecomment commented
Ok, ready for review! 
Avant de merger, attendre demain pour vérifier si le job a bien tourné à l'heure prévue pendant la nuit.

2021-01-06 11:55 UTC, jdauphant commented
@estellecomment la review app crash car on a changé le modele de donnée

2021-01-06 12:55 UTC, estellecomment commented
J'ai fait tourner en prod, donc le data dans la db de prod est a jour.

2021-01-08 11:24 UTC, jdauphant approved these changes

2021-01-08 16:27 UTC, merged